export type Role = 'OWNER' | 'MANAGER' | 'KITCHEN'

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  OWNER: ['ROOMS', 'INVENTORY', 'MENU', 'ORDERS', 'ORDER_STATUS', 'BILLING', 'PAYMENTS', 'TEAM_MANAGEMENT'],
  MANAGER: ['ROOMS', 'INVENTORY', 'MENU', 'ORDERS', 'ORDER_STATUS', 'BILLING', 'PAYMENTS'],
  KITCHEN: ['ORDERS', 'ORDER_STATUS'],
}
